# Generated by Django 2.2.11 on 2020-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('product_image', models.TextField()),
                ('product_name', models.TextField()),
                ('product_text_link', models.TextField()),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=999999999, null=True)),
            ],
        ),
    ]
