# Generated by Django 2.1 on 2020-11-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='day_of_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='day_of_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='month_of_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='month_of_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='payment_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='year_of_expiry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='year_of_subscription',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
