# Generated by Django 2.2.11 on 2020-12-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('otp', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
