# Generated by Django 2.2.11 on 2020-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201107_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('currency', models.TextField()),
                ('website_name', models.TextField()),
                ('website_title', models.TextField()),
                ('facebook', models.TextField()),
                ('instagram', models.TextField()),
                ('twitter', models.TextField()),
                ('country', models.TextField()),
                ('kind_of_products', models.TextField()),
            ],
        ),
    ]
