# Generated by Django 2.2.11 on 2020-11-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201115_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='counter',
            new_name='Visitor_counter',
        ),
    ]
