# Generated by Django 2.2.11 on 2020-11-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201115_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.TextField(null=True),
        ),
    ]
