# Generated by Django 2.1 on 2020-11-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201127_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='day_of_expiry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='day_of_subscription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='month_of_expiry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='month_of_subscription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_of_expiry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='year_of_subscription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
