# Generated by Django 2.2.11 on 2020-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_confirm_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
