# Generated by Django 2.2.11 on 2020-12-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_banner_widget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='product_category',
            new_name='banner_category',
        ),
    ]
