# Generated by Django 2.2.11 on 2021-06-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210110_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='day_of_expiry',
        ),
        migrations.RemoveField(
            model_name='info',
            name='day_of_subscription',
        ),
        migrations.RemoveField(
            model_name='info',
            name='month_of_expiry',
        ),
        migrations.RemoveField(
            model_name='info',
            name='month_of_subscription',
        ),
        migrations.RemoveField(
            model_name='info',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='info',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='info',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='info',
            name='trial',
        ),
        migrations.RemoveField(
            model_name='info',
            name='trial_done',
        ),
        migrations.RemoveField(
            model_name='info',
            name='trial_end',
        ),
        migrations.RemoveField(
            model_name='info',
            name='trial_start',
        ),
        migrations.RemoveField(
            model_name='info',
            name='year_of_expiry',
        ),
        migrations.RemoveField(
            model_name='info',
            name='year_of_subscription',
        ),
    ]
